apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name  }}
  labels:
    app: spring-boot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: 8080
      nodePort: 30007
  selector:
    {{- include "spring-boot.selectorLabels" . | nindent 4 }}