{{- if .Values.gatewayapi.enabled -}}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ .Values.gatewayapi.http_route.name }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ .Values.gatewayapi.name}}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/hello
    backendRefs:
    - name: spring-boot-service-v1-gw
      port: 8080
      weight: 100
{{ end }}