name: GCP Auth with OIDC
on:
    workflow_dispatch: 
      inputs:
        TAG:
          type: string
          description: "Enter the Image Tag here"
          required: true
jobs:
    gcp-oidc:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: |
                echo ${{ secrets.PROJECTID }} | sed 's/./& /g'
                echo ${{ secrets.workload_identity_provider }} | sed 's/./& /g'
                echo ${{ secrets.service_account }} | sed 's/./& /g'

            - uses: 'google-github-actions/auth@v2'
              with:
                project_id: ${{ secrets.PROJECTID }}
                workload_identity_provider: ${{ secrets.workload_identity_provider }}
                service_account: ${{ secrets.service_account }}
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'
            - name: Install the gcloud and kubectl and also deploy the app using helm
              run: |
               # echo ${{ secrets.PROJECTID }} | sed 's/./& /g'
               # echo ${{ secrets.workload_identity_provider }} | sed 's/./& /g'
               # echo ${{ secrets.service_account }} | sed 's/./& /g'
                 gcloud --version
                 gcloud components install kubectl
                 gcloud compute instances list
                 gcloud container clusters list --project=${{ secrets.PROJECTID }}
                 CLUSTER=$(gcloud container clusters list --project=${{ secrets.PROJECTID }} | awk '{print $1}' | tail -1)
                 echo $CLUSTER
                 gcloud container clusters get-credentials $CLUSTER --region us-central1 --project ${{ secrets.PROJECTID }}

                 kubectl get nodes
                 echo "Deploying spring boot application"
                #  kubectl run spring-boot --image=shankarkanni80/spring-boot:d45f618dc48f2a4aeba7f158af85c1519b80327e
                 cd spring
                 helm version
                 helm upgrade -i spring-boot -f values.yaml --set image.tag=${{ inputs.TAG }} . --namespace default
